//
//  typeData.swift
//  Types
//

// Contains all chart data for type effectiveness
import Foundation

let NO_EFFECT_CHART: Dictionary<PokemonType, [PokemonType]> = [
  .NORMAL : [.GHOST],
  .ELECTRIC : [.GROUND],
  .FIGHTING : [.GHOST],
  .POISON : [.STEEL],
  .GROUND : [.FLYING],
  .PSYCHIC : [.DARK],
  .GHOST : [.NORMAL],
  .DRAGON : [.FAIRY]
]

let NOT_EFFECTIVE_CHART: Dictionary<PokemonType, [PokemonType]> = [
  .NORMAL : [.ROCK, .STEEL],
  .FIRE : [.FIRE, .WATER, .ROCK, .DRAGON],
  .WATER : [.WATER, .GRASS, .DRAGON],
  .ELECTRIC : [.ELECTRIC, .GRASS, .DRAGON],
  .GRASS : [.FIRE, .GRASS, .POISON, .FLYING, .BUG, .DRAGON, .STEEL],
  .ICE : [.FIRE, .WATER, .ICE, .STEEL],
  .FIGHTING : [.POISON, .FLYING, .PSYCHIC, .BUG, .FAIRY],
  .POISON : [.POISON, .GROUND, .ROCK, .GHOST],
  .GROUND : [.GRASS, .BUG],
  .FLYING : [.ELECTRIC, .ROCK, .STEEL],
  .PSYCHIC : [.PSYCHIC, .STEEL],
  .BUG : [.FIRE, .FIGHTING, .POISON, .FLYING, .GHOST, .STEEL, .FAIRY],
  .ROCK : [.FIGHTING, .GROUND, .STEEL],
  .GHOST : [.DARK],
  .DRAGON : [.STEEL],
  .DARK : [.FIGHTING, .DARK, .FAIRY],
  .STEEL : [.FIRE, .WATER, .ELECTRIC, .STEEL],
  .FAIRY : [.FIRE, .POISON, .STEEL]
]

let EFFECTIVE_CHART: Dictionary<PokemonType, [PokemonType]> = [
  .NORMAL : [.NORMAL, .FIRE, .WATER, .ELECTRIC, .GRASS, .ICE, .FIGHTING, .POISON, .GROUND, .FLYING, .PSYCHIC, .BUG, .DRAGON, .DARK, .FAIRY],
  .FIRE : [.NORMAL, .ELECTRIC, .FIGHTING, .POISON, .GROUND, .FLYING, .PSYCHIC, .GHOST, .DARK, .FAIRY],
  .WATER : [.NORMAL, .ELECTRIC, .ICE, .FIGHTING, .POISON, .FLYING, .PSYCHIC, .BUG, .GHOST, .DARK, .STEEL, .FAIRY],
  .ELECTRIC : [.NORMAL, .FIRE, .ICE, .FIGHTING, .POISON, .PSYCHIC, .BUG, .ROCK, .GHOST, .DARK, .STEEL, .FAIRY],
  .GRASS : [.NORMAL, .ELECTRIC, .ICE, .FIGHTING, .PSYCHIC, .GHOST, .DARK, .FAIRY],
  .ICE : [.NORMAL, .ELECTRIC, .FIGHTING, .POISON, .PSYCHIC, .BUG, .ROCK, .GHOST, .DARK, .FAIRY],
  .FIGHTING : [.FIRE, .WATER, .ELECTRIC, .GRASS, .FIGHTING, .GROUND, .DRAGON],
  .POISON : [.NORMAL, .FIRE, .WATER, .ELECTRIC, .ICE, .FIGHTING, .FLYING, .PSYCHIC, .BUG, .DRAGON, .DARK],
  .GROUND: [.NORMAL, .WATER, .ICE, .FIGHTING, .GROUND, .PSYCHIC, .GHOST, .DRAGON, .DARK, .FAIRY],
  .FLYING : [.NORMAL, .FIRE, .WATER, .ICE, .POISON, .GROUND, .FLYING, .PSYCHIC, .GHOST, .DRAGON, .DARK, .FAIRY],
  .PSYCHIC : [.NORMAL, .FIRE, .WATER, .ELECTRIC, .GRASS, .ICE, .GROUND, .FLYING, .BUG, .ROCK, .GHOST, .DRAGON, .FAIRY],
  .BUG : [.NORMAL, .WATER, .ELECTRIC, .ICE, .GROUND, .BUG, .ROCK, .DARK],
  .ROCK : [.NORMAL, .WATER, .ELECTRIC, .GRASS, .POISON, .PSYCHIC, .ROCK, .GHOST, .DRAGON, .DARK, .FAIRY],
  .GHOST : [.FIRE, .WATER, .ELECTRIC, .GRASS, .ICE, .FIGHTING, .POISON, .GROUND, .FLYING, .BUG, .ROCK, .DARK, .STEEL, .FAIRY],
  .DRAGON : [.NORMAL, .FIRE, .WATER, .ELECTRIC, .GRASS, .ICE, .FIGHTING, .POISON, .GROUND, .FLYING, .PSYCHIC, .BUG, .ROCK, .GHOST, .DARK],
  .DARK : [.NORMAL, .FIRE, .WATER, .ELECTRIC, .GRASS, .ICE, .POISON, .GROUND, .FLYING, .BUG, .ROCK, .DRAGON, .STEEL],
  .STEEL : [.NORMAL, .GRASS, .FIGHTING, .POISON, .GROUND, .FLYING, .PSYCHIC, .BUG, .GHOST, .DRAGON, .DARK],
  .FAIRY : [.NORMAL, .WATER, .ELECTRIC, .GRASS, .ICE, .GROUND, .FLYING, .PSYCHIC, .BUG, .ROCK, .GHOST, .FAIRY]
]

let VERY_EFFECTIVE_CHART: Dictionary<PokemonType, [PokemonType]> = [
  .FIRE : [.GRASS, .ICE, .BUG, .STEEL],
  .WATER : [.FIRE, .GROUND, .ROCK],
  .ELECTRIC : [.WATER, .FLYING],
  .GRASS : [.WATER, .GROUND, .ROCK],
  .ICE : [.GRASS, .GROUND, .FLYING, .DRAGON],
  .FIGHTING : [.NORMAL, .ICE, .ROCK, .DARK, .STEEL],
  .POISON : [.GRASS, .FAIRY],
  .GROUND : [.FIRE, .ELECTRIC, .POISON, .ROCK, .STEEL],
  .FLYING : [.GRASS, .FIGHTING, .BUG],
  .PSYCHIC : [.FIGHTING, .POISON],
  .BUG : [.GRASS, .PSYCHIC, .DARK],
  .ROCK : [.FIRE, .ICE, .FLYING, .BUG],
  .GHOST : [.PSYCHIC, .GHOST],
  .DRAGON : [.DRAGON],
  .DARK : [.PSYCHIC, .GHOST],
  .STEEL : [.ICE, .ROCK, .FAIRY],
  .FAIRY : [.FIGHTING, .DRAGON, .DARK]
]
